###

# @name testpage
GET http://{{host}}

###

# @name spec
GET http://{{host}}/spec

###

# @name getclassifications
GET http://{{host}}/classification

###

# @name getprojects
GET http://{{host}}/projects

###

# @name create_project
POST http://{{host}}/create_project
Content-Type: application/json

{
    "project_name": "test_project"
}

###

# Initialize erp_project
# @name init_erp_project
POST http://{{host}}/init_project
Content-Type: application/json

{
  "project_name": "erp"
}

###

# @name getmappings
GET http://{{host}}/mappings

###

@mapping_id = {{getmappings.response.body.mappings[1].id}}

# @name getmapping
GET http://{{host}}/mapping/{{mapping_id}}

###

# @name getmappingfields
GET http://{{host}}/mapping/{{mapping_id}}/fields

###

@field_id = {{getmapping.response.body.fields[0].id}}
@targetsame = {{getmapping.response.body.fields[0].id}}
@targetdiff = {{getmapping.response.body.fields[1].id}}

###

# @name post_copy_from
POST http://{{host}}/mapping/{{mapping_id}}/field/{{field_id}}/classification
Content-Type: application/json

{
    "action": "copy_from",
    "target": "{{targetdiff}}"
}

###


# @name post_copy_to
POST http://{{host}}/mapping/{{mapping_id}}/field/{{field_id}}/classification
Content-Type: application/json

{
    "action": "copy_to",
    "target": "{{targetdiff}}"
}

###

# @name post_fixed

POST http://{{host}}/mapping/{{mapping_id}}/field/{{field_id}}/classification
Content-Type: application/json

{
    "action": "fixed",
    "fixed": "fixed-value"
}

###

# @name post_use

POST http://{{host}}/mapping/{{mapping_id}}/field/{{field_id}}/classification
Content-Type: application/json

{
    "action": "use"
}

###

# @name post_not_use

POST http://{{host}}/mapping/{{mapping_id}}/field/{{field_id}}/classification
Content-Type: application/json

{
    "action": "not_use"
}

###

# @name post_empty

POST http://{{host}}/mapping/{{mapping_id}}/field/{{field_id}}/classification
Content-Type: application/json

{
    "action": "empty"
}

