# This is a basic workflow to help you get started with Actions

name: Run Unittests

# Controls when the action will run.
on:
  push:
    paths: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pytest
        run: pip install pytest

      - name: Install dependencies
        run: pip install -e .
        working-directory: ./service

      - name: Run tests
        run: pytest
